services:
  excalidraw:
    image: excalidraw/excalidraw:latest
    container_name: excalidraw-app
    healthcheck:
      disable: true
    expose:
      - "80"
    environment:
      BACKEND_V2_GET_URL: https://draw.mkcoop.com/api/v2/scenes/
      BACKEND_V2_POST_URL: https://draw.mkcoop.com/api/v2/scenes/
      LIBRARY_URL: https://libraries.excalidraw.com
      LIBRARY_BACKEND: https://us-central1-excalidraw-room-persistence.cloudfunctions.net/libraries
      SOCKET_SERVER_URL: https://draw.mkcoop.com/
      STORAGE_BACKEND: "http"
      HTTP_STORAGE_BACKEND_URL: "https://draw.mkcoop.com/api/v2"
    networks:
      - excalidraw-net
    restart: unless-stopped

  excalidraw-storage-backend:
    image: kiliandeca/excalidraw-storage-backend
    container_name: excalidraw-storage
    expose:
      - "8080"
    environment:
      STORAGE_URI: redis://redis:6379
    depends_on:
      - redis
    networks:
      - excalidraw-net
    restart: unless-stopped

  excalidraw-room:
    image: excalidraw/excalidraw-room
    container_name: excalidraw-room
    expose:
      - "80"
    networks:
      - excalidraw-net
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: excalidraw-redis
    expose:
      - "6379"
    networks:
      - excalidraw-net
    restart: unless-stopped

networks:
  excalidraw-net: